Vagrant.configure("2") do |config|

    config.vm.network :forwarded_port, guest: 5000, host: 5000

    config.vm.provider "docker" do |d|
        d.image = "registry:latest"
        d.volumes = ["/vagrant:/data"]
        d.ports = ["5000:5000"]
        d.vagrant_vagrantfile = "../Vagrantfile"
    end

end
